# Generated by Django 3.1.2 on 2020-11-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=19, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
